FROM nginx
COPY conf.d/nginx.conf /etc/nginx/nginx.conf
copy src/ usr/share/nginx/html
RUN apt-get update
RUN apt-get -y install nodejs
#RUN apt-get -y install python
#RUN apt-get -y install curl software-properties-common git build-essential
#RUN curl --silent --location https://deb.nodesource.com/setup_8.x | bash -
#RUN apt-get -y install nodejs


#RUN npm install

se changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
#ADD package.json /angularApp/package.json
#RUN npm install -g node-gyp
#RUN npm run build
#RUN cat /root/.npm/_logs/2017-06-17T07_39_59_569Z-debug.log
#RUN rm /usr/share/nginx/html/*
#RUN cp -r build/* /usr/share/nginx/html/
#COPY src/ /usr/share/nginx/html

