# Generated by Django 3.2 on 2021-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminUser',
        ),
    ]
