# Generated by Django 3.2 on 2021-04-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0002_rename_admin_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=30)),
                ('user_lname', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('reset_password_times', models.CharField(max_length=30)),
                ('isSuper_admin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('isSub_admin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('user_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('usertype_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('usertype_name', models.CharField(max_length=20)),
                ('usertype_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapplication.usertype'),
        ),
    ]
