# Generated by Django 3.2 on 2021-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0003_auto_20210427_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_times',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
