# Generated by Django 3.2 on 2021-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0009_alter_user_reset_password_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=100),
        ),
    ]
