# Generated by Django 3.2 on 2021-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0010_alter_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldetails',
            name='edu_details_status',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='isSub_admin',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='isSuper_admin',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='usertype_status',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10),
        ),
    ]
