# Generated by Django 3.2 on 2021-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0012_auto_20210505_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldetails',
            name='edu_details_status',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=10),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='usertype_status',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=10),
        ),
    ]
