# Generated by Django 3.2 on 2021-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0013_auto_20210505_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_auth_stat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_verify_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
