# Generated by Django 3.2 on 2021-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0014_auto_20210506_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=30)),
                ('user_lname', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_password', models.CharField(max_length=100)),
                ('reset_password_times', models.IntegerField(default=0)),
                ('user_token', models.CharField(max_length=255, null=True)),
                ('user_fcode', models.CharField(max_length=10, null=True)),
                ('user_verify_code', models.CharField(max_length=10, null=True)),
                ('user_auth_stat', models.CharField(max_length=10, null=True)),
                ('isSuper_admin', models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10)),
                ('isSub_admin', models.CharField(choices=[('y', 'y'), ('n', 'n')], max_length=10)),
                ('user_status', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='EducationalDetails',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
