# Generated by Django 3.2 on 2021-05-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0015_auto_20210506_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeUser',
            fields=[
                ('college_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('college_represent_fname', models.CharField(max_length=30)),
                ('college_represent_lname', models.CharField(max_length=30)),
                ('college_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('college_password', models.CharField(max_length=100)),
                ('college_fcode', models.CharField(max_length=100, null=True)),
                ('college_verify_code', models.CharField(max_length=10, null=True)),
                ('college_auth_stat', models.CharField(default='false', max_length=100)),
                ('college_status', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=10)),
            ],
        ),
    ]
