# Generated by Django 3.2 on 2021-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0019_collegeuser_representative_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='is_deleted',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10),
        ),
    ]
