# Generated by Django 3.2 on 2021-05-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0020_collegeuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collegeuser',
            name='college_auth_stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collegeuser',
            name='representative_status',
            field=models.BooleanField(default=True),
        ),
    ]
