# Generated by Django 3.2 on 2021-05-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0021_auto_20210510_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterUser',
            fields=[
                ('recruiter_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recruiter_fname', models.CharField(max_length=100)),
                ('recruiter_lname', models.CharField(max_length=100)),
                ('recruiter_company', models.CharField(max_length=100)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('recruiter_phone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('recruiter_password', models.CharField(max_length=100)),
                ('recruiter_fcode', models.CharField(max_length=100, null=True)),
                ('recruiter_verify_code', models.CharField(max_length=10, null=True)),
                ('recruiter_auth_stat', models.BooleanField(default=False)),
                ('recruiter_status', models.BooleanField(default=True)),
                ('company_logo', models.ImageField(upload_to='')),
                ('is_deleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=10)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapplication.adminuser')),
            ],
        ),
    ]
