# Generated by Django 3.2 on 2021-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0022_recruiteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteruser',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
