# Generated by Django 3.2 on 2021-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0023_alter_recruiteruser_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeuser',
            name='representative_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='recruiteruser',
            name='recruiter_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
