# Generated by Django 3.2 on 2021-05-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0024_auto_20210512_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiteruser',
            old_name='recruiter_auth_stat',
            new_name='is_verified',
        ),
    ]
