# Generated by Django 3.2 on 2021-05-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0025_rename_recruiter_auth_stat_recruiteruser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiteruser',
            old_name='is_verified',
            new_name='recruiter_auth_stat',
        ),
    ]
